modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="monsters_anywhere"
version="1.0.0"
displayName="Monsters anywhere"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="storm, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.monsters_anywhere]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.monsters_anywhere]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



